// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"
	"viktor/ent"
)

// The AbteilungFunc type is an adapter to allow the use of ordinary
// function as Abteilung mutator.
type AbteilungFunc func(context.Context, *ent.AbteilungMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AbteilungFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AbteilungMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AbteilungMutation", m)
}

// The AngebotFunc type is an adapter to allow the use of ordinary
// function as Angebot mutator.
type AngebotFunc func(context.Context, *ent.AngebotMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AngebotFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AngebotMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AngebotMutation", m)
}

// The AnsprechpartnerFunc type is an adapter to allow the use of ordinary
// function as Ansprechpartner mutator.
type AnsprechpartnerFunc func(context.Context, *ent.AnsprechpartnerMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AnsprechpartnerFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AnsprechpartnerMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AnsprechpartnerMutation", m)
}

// The AusstellerFunc type is an adapter to allow the use of ordinary
// function as Aussteller mutator.
type AusstellerFunc func(context.Context, *ent.AusstellerMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AusstellerFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AusstellerMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AusstellerMutation", m)
}

// The EinkaufFunc type is an adapter to allow the use of ordinary
// function as Einkauf mutator.
type EinkaufFunc func(context.Context, *ent.EinkaufMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f EinkaufFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.EinkaufMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.EinkaufMutation", m)
}

// The JobFunc type is an adapter to allow the use of ordinary
// function as Job mutator.
type JobFunc func(context.Context, *ent.JobMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f JobFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.JobMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.JobMutation", m)
}

// The LieferantFunc type is an adapter to allow the use of ordinary
// function as Lieferant mutator.
type LieferantFunc func(context.Context, *ent.LieferantMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LieferantFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.LieferantMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LieferantMutation", m)
}

// The MitarbeiterFunc type is an adapter to allow the use of ordinary
// function as Mitarbeiter mutator.
type MitarbeiterFunc func(context.Context, *ent.MitarbeiterMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MitarbeiterFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MitarbeiterMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MitarbeiterMutation", m)
}

// The PartnerFunc type is an adapter to allow the use of ordinary
// function as Partner mutator.
type PartnerFunc func(context.Context, *ent.PartnerMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PartnerFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PartnerMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PartnerMutation", m)
}

// The PdfFunc type is an adapter to allow the use of ordinary
// function as Pdf mutator.
type PdfFunc func(context.Context, *ent.PdfMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PdfFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PdfMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PdfMutation", m)
}

// The StatuFunc type is an adapter to allow the use of ordinary
// function as Statu mutator.
type StatuFunc func(context.Context, *ent.StatuMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StatuFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.StatuMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StatuMutation", m)
}

// The WarenlieferungFunc type is an adapter to allow the use of ordinary
// function as Warenlieferung mutator.
type WarenlieferungFunc func(context.Context, *ent.WarenlieferungMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f WarenlieferungFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.WarenlieferungMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.WarenlieferungMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
