// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class ArchiveResult {
    /**
     * Creates a new ArchiveResult instance.
     * @param {Partial<ArchiveResult>} [$$source = {}] - The source object to create the ArchiveResult.
     */
    constructor($$source = {}) {
        if (!("Id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Id"] = 0;
        }
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchiveResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArchiveResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArchiveResult(/** @type {Partial<ArchiveResult>} */($$parsedSource));
    }
}
