// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class SearchResult {
    "SG_Adressen_PK": number;
    "Suchbegriff": string | null;
    "KundNr": string | null;
    "LiefNr": string | null;
    "Homepage": string | null;
    "Telefon1": string | null;
    "Telefon2": string | null;
    "Mobiltelefon1": string | null;
    "Mobiltelefon2": string | null;
    "EMail1": string | null;
    "EMail2": string | null;
    "KundUmsatz": number | null;
    "LiefUmsatz": number | null;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("SG_Adressen_PK" in $$source)) {
            this["SG_Adressen_PK"] = 0;
        }
        if (!("Suchbegriff" in $$source)) {
            this["Suchbegriff"] = null;
        }
        if (!("KundNr" in $$source)) {
            this["KundNr"] = null;
        }
        if (!("LiefNr" in $$source)) {
            this["LiefNr"] = null;
        }
        if (!("Homepage" in $$source)) {
            this["Homepage"] = null;
        }
        if (!("Telefon1" in $$source)) {
            this["Telefon1"] = null;
        }
        if (!("Telefon2" in $$source)) {
            this["Telefon2"] = null;
        }
        if (!("Mobiltelefon1" in $$source)) {
            this["Mobiltelefon1"] = null;
        }
        if (!("Mobiltelefon2" in $$source)) {
            this["Mobiltelefon2"] = null;
        }
        if (!("EMail1" in $$source)) {
            this["EMail1"] = null;
        }
        if (!("EMail2" in $$source)) {
            this["EMail2"] = null;
        }
        if (!("KundUmsatz" in $$source)) {
            this["KundUmsatz"] = null;
        }
        if (!("LiefUmsatz" in $$source)) {
            this["LiefUmsatz"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

export class User {
    "Name": string | null;
    "Vorname": string | null;

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = null;
        }
        if (!("Vorname" in $$source)) {
            this["Vorname"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User($$parsedSource as Partial<User>);
    }
}
