// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class Ansprechpartner {
    /**
     * Creates a new Ansprechpartner instance.
     * @param {Partial<Ansprechpartner>} [$$source = {}] - The source object to create the Ansprechpartner.
     */
    constructor($$source = {}) {
        if (!("Id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Id"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Telefon" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["Telefon"] = null;
        }
        if (!("Mobil" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["Mobil"] = null;
        }
        if (!("Mail" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["Mail"] = null;
        }
        if (!("LieferantenId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LieferantenId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Ansprechpartner instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Ansprechpartner}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Ansprechpartner(/** @type {Partial<Ansprechpartner>} */($$parsedSource));
    }
}

export class Kanban {
    /**
     * Creates a new Kanban instance.
     * @param {Partial<Kanban>} [$$source = {}] - The source object to create the Kanban.
     */
    constructor($$source = {}) {
        if (!("Id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Id"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("UserId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UserId"] = "";
        }
        if (!("Posts" in $$source)) {
            /**
             * @member
             * @type {Post[]}
             */
            this["Posts"] = [];
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["UpdatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Kanban instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Kanban}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Posts" in $$parsedSource) {
            $$parsedSource["Posts"] = $$createField3_0($$parsedSource["Posts"]);
        }
        return new Kanban(/** @type {Partial<Kanban>} */($$parsedSource));
    }
}

export class Lieferant {
    /**
     * Creates a new Lieferant instance.
     * @param {Partial<Lieferant>} [$$source = {}] - The source object to create the Lieferant.
     */
    constructor($$source = {}) {
        if (!("Id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Id"] = "";
        }
        if (!("Firma" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Firma"] = "";
        }
        if (!("Kundennummer" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["Kundennummer"] = null;
        }
        if (!("Webseite" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["Webseite"] = null;
        }
        if (!("Ansprechpartner" in $$source)) {
            /**
             * @member
             * @type {Ansprechpartner[]}
             */
            this["Ansprechpartner"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Lieferant instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Lieferant}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Ansprechpartner" in $$parsedSource) {
            $$parsedSource["Ansprechpartner"] = $$createField4_0($$parsedSource["Ansprechpartner"]);
        }
        return new Lieferant(/** @type {Partial<Lieferant>} */($$parsedSource));
    }
}

export class Mitarbeiter {
    /**
     * Creates a new Mitarbeiter instance.
     * @param {Partial<Mitarbeiter>} [$$source = {}] - The source object to create the Mitarbeiter.
     */
    constructor($$source = {}) {
        if (!("Id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Id"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Short" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["Short"] = null;
        }
        if (!("Gruppenwahl" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["Gruppenwahl"] = null;
        }
        if (!("InternTelefon1" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["InternTelefon1"] = null;
        }
        if (!("InternTelefon2" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["InternTelefon2"] = null;
        }
        if (!("FestnetzPrivat" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["FestnetzPrivat"] = null;
        }
        if (!("FestnetzBusiness" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["FestnetzBusiness"] = null;
        }
        if (!("HomeOffice" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["HomeOffice"] = null;
        }
        if (!("MobilBusiness" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["MobilBusiness"] = null;
        }
        if (!("MobilPrivat" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["MobilPrivat"] = null;
        }
        if (!("Email" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["Email"] = null;
        }
        if (!("Azubi" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Azubi"] = false;
        }
        if (!("Geburtstag" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["Geburtstag"] = null;
        }
        if (!("Paypal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Paypal"] = false;
        }
        if (!("Abonniert" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Abonniert"] = false;
        }
        if (!("Geld" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["Geld"] = null;
        }
        if (!("Pfand" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["Pfand"] = null;
        }
        if (!("Dinge" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["Dinge"] = null;
        }
        if (!("Abgeschickt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["Abgeschickt"] = null;
        }
        if (!("Bild1" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["Bild1"] = null;
        }
        if (!("Bild2" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["Bild2"] = null;
        }
        if (!("Bild3" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["Bild3"] = null;
        }
        if (!("Bild1Date" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["Bild1Date"] = null;
        }
        if (!("Bild2Date" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["Bild2Date"] = null;
        }
        if (!("Bild3Date" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["Bild3Date"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mitarbeiter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Mitarbeiter}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Mitarbeiter(/** @type {Partial<Mitarbeiter>} */($$parsedSource));
    }
}

export class Post {
    /**
     * Creates a new Post instance.
     * @param {Partial<Post>} [$$source = {}] - The source object to create the Post.
     */
    constructor($$source = {}) {
        if (!("Id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Id"] = "";
        }
        if (!("KanbanId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["KanbanId"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["Description"] = null;
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Status"] = "";
        }
        if (!("Importance" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Importance"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["UpdatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Post instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Post}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Post(/** @type {Partial<Post>} */($$parsedSource));
    }
}

export class User {
    /**
     * Creates a new User instance.
     * @param {Partial<User>} [$$source = {}] - The source object to create the User.
     */
    constructor($$source = {}) {
        if (!("Id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Id"] = "";
        }
        if (!("Password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Password"] = "";
        }
        if (!("Mail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Mail"] = "";
        }
        if (!("MitarbeiterId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["MitarbeiterId"] = "";
        }
        if (!("Mitarbeiter" in $$source)) {
            /**
             * @member
             * @type {Mitarbeiter}
             */
            this["Mitarbeiter"] = (new Mitarbeiter());
        }
        if (!("Boards" in $$source)) {
            /**
             * @member
             * @type {Kanban[]}
             */
            this["Boards"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {User}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mitarbeiter" in $$parsedSource) {
            $$parsedSource["Mitarbeiter"] = $$createField4_0($$parsedSource["Mitarbeiter"]);
        }
        if ("Boards" in $$parsedSource) {
            $$parsedSource["Boards"] = $$createField5_0($$parsedSource["Boards"]);
        }
        return new User(/** @type {Partial<User>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Post.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Ansprechpartner.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Mitarbeiter.createFrom;
const $$createType5 = Kanban.createFrom;
const $$createType6 = $Create.Array($$createType5);
