// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class Ansprechpartner {
    "Id": string;
    "Name": string;
    "Telefon": string | null;
    "Mobil": string | null;
    "Mail": string | null;
    "LieferantenId": string;

    /** Creates a new Ansprechpartner instance. */
    constructor($$source: Partial<Ansprechpartner> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Telefon" in $$source)) {
            this["Telefon"] = null;
        }
        if (!("Mobil" in $$source)) {
            this["Mobil"] = null;
        }
        if (!("Mail" in $$source)) {
            this["Mail"] = null;
        }
        if (!("LieferantenId" in $$source)) {
            this["LieferantenId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Ansprechpartner instance from a string or object.
     */
    static createFrom($$source: any = {}): Ansprechpartner {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Ansprechpartner($$parsedSource as Partial<Ansprechpartner>);
    }
}

export class Kanban {
    "Id": string;
    "Name": string;
    "UserId": string;
    "Posts": Post[];
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;

    /** Creates a new Kanban instance. */
    constructor($$source: Partial<Kanban> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("UserId" in $$source)) {
            this["UserId"] = "";
        }
        if (!("Posts" in $$source)) {
            this["Posts"] = [];
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Kanban instance from a string or object.
     */
    static createFrom($$source: any = {}): Kanban {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Posts" in $$parsedSource) {
            $$parsedSource["Posts"] = $$createField3_0($$parsedSource["Posts"]);
        }
        return new Kanban($$parsedSource as Partial<Kanban>);
    }
}

export class Lieferant {
    "Id": string;
    "Firma": string;
    "Kundennummer": string | null;
    "Webseite": string | null;
    "Ansprechpartner": Ansprechpartner[];

    /** Creates a new Lieferant instance. */
    constructor($$source: Partial<Lieferant> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Firma" in $$source)) {
            this["Firma"] = "";
        }
        if (!("Kundennummer" in $$source)) {
            this["Kundennummer"] = null;
        }
        if (!("Webseite" in $$source)) {
            this["Webseite"] = null;
        }
        if (!("Ansprechpartner" in $$source)) {
            this["Ansprechpartner"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Lieferant instance from a string or object.
     */
    static createFrom($$source: any = {}): Lieferant {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Ansprechpartner" in $$parsedSource) {
            $$parsedSource["Ansprechpartner"] = $$createField4_0($$parsedSource["Ansprechpartner"]);
        }
        return new Lieferant($$parsedSource as Partial<Lieferant>);
    }
}

export class Mitarbeiter {
    "Id": string;
    "Name": string;
    "Short": string | null;
    "Gruppenwahl": string | null;
    "InternTelefon1": string | null;
    "InternTelefon2": string | null;
    "FestnetzPrivat": string | null;
    "FestnetzBusiness": string | null;
    "HomeOffice": string | null;
    "MobilBusiness": string | null;
    "MobilPrivat": string | null;
    "Email": string | null;
    "Azubi": boolean;
    "Geburtstag": time$0.Time | null;
    "Paypal": boolean;
    "Abonniert": boolean;
    "Geld": string | null;
    "Pfand": string | null;
    "Dinge": string | null;
    "Abgeschickt": time$0.Time | null;
    "Bild1": string | null;
    "Bild2": string | null;
    "Bild3": string | null;
    "Bild1Date": time$0.Time | null;
    "Bild2Date": time$0.Time | null;
    "Bild3Date": time$0.Time | null;

    /** Creates a new Mitarbeiter instance. */
    constructor($$source: Partial<Mitarbeiter> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Short" in $$source)) {
            this["Short"] = null;
        }
        if (!("Gruppenwahl" in $$source)) {
            this["Gruppenwahl"] = null;
        }
        if (!("InternTelefon1" in $$source)) {
            this["InternTelefon1"] = null;
        }
        if (!("InternTelefon2" in $$source)) {
            this["InternTelefon2"] = null;
        }
        if (!("FestnetzPrivat" in $$source)) {
            this["FestnetzPrivat"] = null;
        }
        if (!("FestnetzBusiness" in $$source)) {
            this["FestnetzBusiness"] = null;
        }
        if (!("HomeOffice" in $$source)) {
            this["HomeOffice"] = null;
        }
        if (!("MobilBusiness" in $$source)) {
            this["MobilBusiness"] = null;
        }
        if (!("MobilPrivat" in $$source)) {
            this["MobilPrivat"] = null;
        }
        if (!("Email" in $$source)) {
            this["Email"] = null;
        }
        if (!("Azubi" in $$source)) {
            this["Azubi"] = false;
        }
        if (!("Geburtstag" in $$source)) {
            this["Geburtstag"] = null;
        }
        if (!("Paypal" in $$source)) {
            this["Paypal"] = false;
        }
        if (!("Abonniert" in $$source)) {
            this["Abonniert"] = false;
        }
        if (!("Geld" in $$source)) {
            this["Geld"] = null;
        }
        if (!("Pfand" in $$source)) {
            this["Pfand"] = null;
        }
        if (!("Dinge" in $$source)) {
            this["Dinge"] = null;
        }
        if (!("Abgeschickt" in $$source)) {
            this["Abgeschickt"] = null;
        }
        if (!("Bild1" in $$source)) {
            this["Bild1"] = null;
        }
        if (!("Bild2" in $$source)) {
            this["Bild2"] = null;
        }
        if (!("Bild3" in $$source)) {
            this["Bild3"] = null;
        }
        if (!("Bild1Date" in $$source)) {
            this["Bild1Date"] = null;
        }
        if (!("Bild2Date" in $$source)) {
            this["Bild2Date"] = null;
        }
        if (!("Bild3Date" in $$source)) {
            this["Bild3Date"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mitarbeiter instance from a string or object.
     */
    static createFrom($$source: any = {}): Mitarbeiter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Mitarbeiter($$parsedSource as Partial<Mitarbeiter>);
    }
}

export class Post {
    "Id": string;
    "KanbanId": string;
    "Name": string;
    "Description": string | null;
    "Status": string;
    "Importance": string;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;

    /** Creates a new Post instance. */
    constructor($$source: Partial<Post> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("KanbanId" in $$source)) {
            this["KanbanId"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = null;
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }
        if (!("Importance" in $$source)) {
            this["Importance"] = "";
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Post instance from a string or object.
     */
    static createFrom($$source: any = {}): Post {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Post($$parsedSource as Partial<Post>);
    }
}

export class User {
    "Id": string;
    "Passwort": string;
    "Mail": string;
    "MitarbeiterId": string;
    "Mitarbeiter": Mitarbeiter;
    "Boards": Kanban[];

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Passwort" in $$source)) {
            this["Passwort"] = "";
        }
        if (!("Mail" in $$source)) {
            this["Mail"] = "";
        }
        if (!("MitarbeiterId" in $$source)) {
            this["MitarbeiterId"] = "";
        }
        if (!("Mitarbeiter" in $$source)) {
            this["Mitarbeiter"] = (new Mitarbeiter());
        }
        if (!("Boards" in $$source)) {
            this["Boards"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mitarbeiter" in $$parsedSource) {
            $$parsedSource["Mitarbeiter"] = $$createField4_0($$parsedSource["Mitarbeiter"]);
        }
        if ("Boards" in $$parsedSource) {
            $$parsedSource["Boards"] = $$createField5_0($$parsedSource["Boards"]);
        }
        return new User($$parsedSource as Partial<User>);
    }
}

// Private type creation functions
const $$createType0 = Post.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Ansprechpartner.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Mitarbeiter.createFrom;
const $$createType5 = Kanban.createFrom;
const $$createType6 = $Create.Array($$createType5);
