// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class UserData {
    "Name": string | null;
    "Mail": string | null;
    "Id": string | null;
    "UserId": string | null;

    /** Creates a new UserData instance. */
    constructor($$source: Partial<UserData> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = null;
        }
        if (!("Mail" in $$source)) {
            this["Mail"] = null;
        }
        if (!("Id" in $$source)) {
            this["Id"] = null;
        }
        if (!("UserId" in $$source)) {
            this["UserId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserData instance from a string or object.
     */
    static createFrom($$source: any = {}): UserData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserData($$parsedSource as Partial<UserData>);
    }
}
