// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Abteilung struct {
	ent.Schema
}

func (Abteilung) Fields() []ent.Field {
	return []ent.Field{field.String("id"), field.String("name")}
}
func (Abteilung) Edges() []ent.Edge {
	return []ent.Edge{edge.To("mitarbeiters", Mitarbeiter.Type)}
}
func (Abteilung) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Abteilung"}}
}
