// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Ansprechpartner struct {
	ent.Schema
}

func (Ansprechpartner) Fields() []ent.Field {
	return []ent.Field{field.String("id"), field.String("name"), field.String("telefon").Optional(), field.String("mobil").Optional(), field.String("mail").Optional(), field.String("lieferantId").Optional()}
}
func (Ansprechpartner) Edges() []ent.Edge {
	return []ent.Edge{edge.From("lieferant", Lieferant.Type).Ref("ansprechpartners").Unique().Field("lieferantId")}
}
func (Ansprechpartner) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Ansprechpartner"}}
}
