// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Einkauf struct {
	ent.Schema
}

func (Einkauf) Fields() []ent.Field {
	return []ent.Field{field.String("id"), field.Bool("Paypal"), field.Bool("Abonniert"), field.String("Geld").Optional(), field.String("Pfand").Optional(), field.String("Dinge"), field.Time("Abgeschickt"), field.String("Bild1").Optional(), field.String("Bild2").Optional(), field.String("Bild3").Optional()}
}
func (Einkauf) Edges() []ent.Edge {
	return []ent.Edge{edge.To("mitarbeiter", Mitarbeiter.Type).Unique()}
}
func (Einkauf) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Einkauf"}}
}
