// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type Job struct {
	ent.Schema
}

func (Job) Fields() []ent.Field {
	return []ent.Field{field.String("id"), field.String("name"), field.Bool("online")}
}
func (Job) Edges() []ent.Edge {
	return nil
}
func (Job) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Jobs"}}
}
