// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Lieferant struct {
	ent.Schema
}

func (Lieferant) Fields() []ent.Field {
	return []ent.Field{field.String("id"), field.String("Firma"), field.String("Kundennummer").Optional(), field.String("Webseite").Optional()}
}
func (Lieferant) Edges() []ent.Edge {
	return []ent.Edge{edge.To("ansprechpartners", Ansprechpartner.Type)}
}
func (Lieferant) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Lieferant"}}
}
