// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type Partner struct {
	ent.Schema
}

func (Partner) Fields() []ent.Field {
	return []ent.Field{field.String("id"), field.String("name"), field.String("link"), field.String("image")}
}
func (Partner) Edges() []ent.Edge {
	return nil
}
func (Partner) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Partner"}}
}
