// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type Warenlieferung struct {
	ent.Schema
}

func (Warenlieferung) Fields() []ent.Field {
	return []ent.Field{field.Int32("id"), field.String("Name"), field.Time("angelegt"), field.Time("geliefert").Optional(), field.Float32("AlterPreis").Optional(), field.Float32("NeuerPreis").Optional(), field.Time("Preis").Optional(), field.String("Artikelnummer")}
}
func (Warenlieferung) Edges() []ent.Edge {
	return nil
}
func (Warenlieferung) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "Warenlieferung"}}
}
