[Database]
URL = "root:maserpassword@tcp(localhost:3306)/viktor?parseTime=true"

[Folder]
Upload = "tmp"
Archive = "archive"

[Mail]
From = "noreply@example.com"
Server = "smtp.myserver.com"
Port = 465
User = "superadmin"
Password = "mysecurepassword"

[Sage]
Server = "SQL\\SAGE"
Port = 1433
User = "sa"
Password = "mysecretpassword123"
Database = "Mandant1"
