// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"viktor/ent/abteilung"
	"viktor/ent/mitarbeiter"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AbteilungCreate is the builder for creating a Abteilung entity.
type AbteilungCreate struct {
	config
	mutation *AbteilungMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ac *AbteilungCreate) SetName(s string) *AbteilungCreate {
	ac.mutation.SetName(s)
	return ac
}

// SetID sets the "id" field.
func (ac *AbteilungCreate) SetID(s string) *AbteilungCreate {
	ac.mutation.SetID(s)
	return ac
}

// AddMitarbeiterIDs adds the "mitarbeiters" edge to the Mitarbeiter entity by IDs.
func (ac *AbteilungCreate) AddMitarbeiterIDs(ids ...string) *AbteilungCreate {
	ac.mutation.AddMitarbeiterIDs(ids...)
	return ac
}

// AddMitarbeiters adds the "mitarbeiters" edges to the Mitarbeiter entity.
func (ac *AbteilungCreate) AddMitarbeiters(m ...*Mitarbeiter) *AbteilungCreate {
	ids := make([]string, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return ac.AddMitarbeiterIDs(ids...)
}

// Mutation returns the AbteilungMutation object of the builder.
func (ac *AbteilungCreate) Mutation() *AbteilungMutation {
	return ac.mutation
}

// Save creates the Abteilung in the database.
func (ac *AbteilungCreate) Save(ctx context.Context) (*Abteilung, error) {
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AbteilungCreate) SaveX(ctx context.Context) *Abteilung {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AbteilungCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AbteilungCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AbteilungCreate) check() error {
	if _, ok := ac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Abteilung.name"`)}
	}
	return nil
}

func (ac *AbteilungCreate) sqlSave(ctx context.Context) (*Abteilung, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Abteilung.ID type: %T", _spec.ID.Value)
		}
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AbteilungCreate) createSpec() (*Abteilung, *sqlgraph.CreateSpec) {
	var (
		_node = &Abteilung{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(abteilung.Table, sqlgraph.NewFieldSpec(abteilung.FieldID, field.TypeString))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.Name(); ok {
		_spec.SetField(abteilung.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := ac.mutation.MitarbeitersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   abteilung.MitarbeitersTable,
			Columns: []string{abteilung.MitarbeitersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mitarbeiter.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AbteilungCreateBulk is the builder for creating many Abteilung entities in bulk.
type AbteilungCreateBulk struct {
	config
	err      error
	builders []*AbteilungCreate
}

// Save creates the Abteilung entities in the database.
func (acb *AbteilungCreateBulk) Save(ctx context.Context) ([]*Abteilung, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Abteilung, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AbteilungMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AbteilungCreateBulk) SaveX(ctx context.Context) []*Abteilung {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AbteilungCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AbteilungCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
