// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"viktor/ent/abteilung"
	"viktor/ent/mitarbeiter"
	"viktor/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AbteilungQuery is the builder for querying Abteilung entities.
type AbteilungQuery struct {
	config
	ctx              *QueryContext
	order            []abteilung.OrderOption
	inters           []Interceptor
	predicates       []predicate.Abteilung
	withMitarbeiters *MitarbeiterQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AbteilungQuery builder.
func (aq *AbteilungQuery) Where(ps ...predicate.Abteilung) *AbteilungQuery {
	aq.predicates = append(aq.predicates, ps...)
	return aq
}

// Limit the number of records to be returned by this query.
func (aq *AbteilungQuery) Limit(limit int) *AbteilungQuery {
	aq.ctx.Limit = &limit
	return aq
}

// Offset to start from.
func (aq *AbteilungQuery) Offset(offset int) *AbteilungQuery {
	aq.ctx.Offset = &offset
	return aq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aq *AbteilungQuery) Unique(unique bool) *AbteilungQuery {
	aq.ctx.Unique = &unique
	return aq
}

// Order specifies how the records should be ordered.
func (aq *AbteilungQuery) Order(o ...abteilung.OrderOption) *AbteilungQuery {
	aq.order = append(aq.order, o...)
	return aq
}

// QueryMitarbeiters chains the current query on the "mitarbeiters" edge.
func (aq *AbteilungQuery) QueryMitarbeiters() *MitarbeiterQuery {
	query := (&MitarbeiterClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(abteilung.Table, abteilung.FieldID, selector),
			sqlgraph.To(mitarbeiter.Table, mitarbeiter.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, abteilung.MitarbeitersTable, abteilung.MitarbeitersColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Abteilung entity from the query.
// Returns a *NotFoundError when no Abteilung was found.
func (aq *AbteilungQuery) First(ctx context.Context) (*Abteilung, error) {
	nodes, err := aq.Limit(1).All(setContextOp(ctx, aq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{abteilung.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aq *AbteilungQuery) FirstX(ctx context.Context) *Abteilung {
	node, err := aq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Abteilung ID from the query.
// Returns a *NotFoundError when no Abteilung ID was found.
func (aq *AbteilungQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = aq.Limit(1).IDs(setContextOp(ctx, aq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{abteilung.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aq *AbteilungQuery) FirstIDX(ctx context.Context) string {
	id, err := aq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Abteilung entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Abteilung entity is found.
// Returns a *NotFoundError when no Abteilung entities are found.
func (aq *AbteilungQuery) Only(ctx context.Context) (*Abteilung, error) {
	nodes, err := aq.Limit(2).All(setContextOp(ctx, aq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{abteilung.Label}
	default:
		return nil, &NotSingularError{abteilung.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aq *AbteilungQuery) OnlyX(ctx context.Context) *Abteilung {
	node, err := aq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Abteilung ID in the query.
// Returns a *NotSingularError when more than one Abteilung ID is found.
// Returns a *NotFoundError when no entities are found.
func (aq *AbteilungQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = aq.Limit(2).IDs(setContextOp(ctx, aq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{abteilung.Label}
	default:
		err = &NotSingularError{abteilung.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aq *AbteilungQuery) OnlyIDX(ctx context.Context) string {
	id, err := aq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Abteilungs.
func (aq *AbteilungQuery) All(ctx context.Context) ([]*Abteilung, error) {
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryAll)
	if err := aq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Abteilung, *AbteilungQuery]()
	return withInterceptors[[]*Abteilung](ctx, aq, qr, aq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aq *AbteilungQuery) AllX(ctx context.Context) []*Abteilung {
	nodes, err := aq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Abteilung IDs.
func (aq *AbteilungQuery) IDs(ctx context.Context) (ids []string, err error) {
	if aq.ctx.Unique == nil && aq.path != nil {
		aq.Unique(true)
	}
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryIDs)
	if err = aq.Select(abteilung.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aq *AbteilungQuery) IDsX(ctx context.Context) []string {
	ids, err := aq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aq *AbteilungQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryCount)
	if err := aq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aq, querierCount[*AbteilungQuery](), aq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aq *AbteilungQuery) CountX(ctx context.Context) int {
	count, err := aq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aq *AbteilungQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryExist)
	switch _, err := aq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aq *AbteilungQuery) ExistX(ctx context.Context) bool {
	exist, err := aq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AbteilungQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aq *AbteilungQuery) Clone() *AbteilungQuery {
	if aq == nil {
		return nil
	}
	return &AbteilungQuery{
		config:           aq.config,
		ctx:              aq.ctx.Clone(),
		order:            append([]abteilung.OrderOption{}, aq.order...),
		inters:           append([]Interceptor{}, aq.inters...),
		predicates:       append([]predicate.Abteilung{}, aq.predicates...),
		withMitarbeiters: aq.withMitarbeiters.Clone(),
		// clone intermediate query.
		sql:  aq.sql.Clone(),
		path: aq.path,
	}
}

// WithMitarbeiters tells the query-builder to eager-load the nodes that are connected to
// the "mitarbeiters" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AbteilungQuery) WithMitarbeiters(opts ...func(*MitarbeiterQuery)) *AbteilungQuery {
	query := (&MitarbeiterClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withMitarbeiters = query
	return aq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Abteilung.Query().
//		GroupBy(abteilung.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aq *AbteilungQuery) GroupBy(field string, fields ...string) *AbteilungGroupBy {
	aq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AbteilungGroupBy{build: aq}
	grbuild.flds = &aq.ctx.Fields
	grbuild.label = abteilung.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Abteilung.Query().
//		Select(abteilung.FieldName).
//		Scan(ctx, &v)
func (aq *AbteilungQuery) Select(fields ...string) *AbteilungSelect {
	aq.ctx.Fields = append(aq.ctx.Fields, fields...)
	sbuild := &AbteilungSelect{AbteilungQuery: aq}
	sbuild.label = abteilung.Label
	sbuild.flds, sbuild.scan = &aq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AbteilungSelect configured with the given aggregations.
func (aq *AbteilungQuery) Aggregate(fns ...AggregateFunc) *AbteilungSelect {
	return aq.Select().Aggregate(fns...)
}

func (aq *AbteilungQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aq); err != nil {
				return err
			}
		}
	}
	for _, f := range aq.ctx.Fields {
		if !abteilung.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aq.path != nil {
		prev, err := aq.path(ctx)
		if err != nil {
			return err
		}
		aq.sql = prev
	}
	return nil
}

func (aq *AbteilungQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Abteilung, error) {
	var (
		nodes       = []*Abteilung{}
		_spec       = aq.querySpec()
		loadedTypes = [1]bool{
			aq.withMitarbeiters != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Abteilung).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Abteilung{config: aq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := aq.withMitarbeiters; query != nil {
		if err := aq.loadMitarbeiters(ctx, query, nodes,
			func(n *Abteilung) { n.Edges.Mitarbeiters = []*Mitarbeiter{} },
			func(n *Abteilung, e *Mitarbeiter) { n.Edges.Mitarbeiters = append(n.Edges.Mitarbeiters, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (aq *AbteilungQuery) loadMitarbeiters(ctx context.Context, query *MitarbeiterQuery, nodes []*Abteilung, init func(*Abteilung), assign func(*Abteilung, *Mitarbeiter)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Abteilung)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(mitarbeiter.FieldAbteilungId)
	}
	query.Where(predicate.Mitarbeiter(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(abteilung.MitarbeitersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AbteilungId
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "abteilungId" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (aq *AbteilungQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aq.querySpec()
	_spec.Node.Columns = aq.ctx.Fields
	if len(aq.ctx.Fields) > 0 {
		_spec.Unique = aq.ctx.Unique != nil && *aq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aq.driver, _spec)
}

func (aq *AbteilungQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(abteilung.Table, abteilung.Columns, sqlgraph.NewFieldSpec(abteilung.FieldID, field.TypeString))
	_spec.From = aq.sql
	if unique := aq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aq.path != nil {
		_spec.Unique = true
	}
	if fields := aq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, abteilung.FieldID)
		for i := range fields {
			if fields[i] != abteilung.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aq *AbteilungQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aq.driver.Dialect())
	t1 := builder.Table(abteilung.Table)
	columns := aq.ctx.Fields
	if len(columns) == 0 {
		columns = abteilung.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aq.sql != nil {
		selector = aq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aq.ctx.Unique != nil && *aq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aq.predicates {
		p(selector)
	}
	for _, p := range aq.order {
		p(selector)
	}
	if offset := aq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AbteilungGroupBy is the group-by builder for Abteilung entities.
type AbteilungGroupBy struct {
	selector
	build *AbteilungQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (agb *AbteilungGroupBy) Aggregate(fns ...AggregateFunc) *AbteilungGroupBy {
	agb.fns = append(agb.fns, fns...)
	return agb
}

// Scan applies the selector query and scans the result into the given value.
func (agb *AbteilungGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, agb.build.ctx, ent.OpQueryGroupBy)
	if err := agb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AbteilungQuery, *AbteilungGroupBy](ctx, agb.build, agb, agb.build.inters, v)
}

func (agb *AbteilungGroupBy) sqlScan(ctx context.Context, root *AbteilungQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(agb.fns))
	for _, fn := range agb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*agb.flds)+len(agb.fns))
		for _, f := range *agb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*agb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := agb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AbteilungSelect is the builder for selecting fields of Abteilung entities.
type AbteilungSelect struct {
	*AbteilungQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (as *AbteilungSelect) Aggregate(fns ...AggregateFunc) *AbteilungSelect {
	as.fns = append(as.fns, fns...)
	return as
}

// Scan applies the selector query and scans the result into the given value.
func (as *AbteilungSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, as.ctx, ent.OpQuerySelect)
	if err := as.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AbteilungQuery, *AbteilungSelect](ctx, as.AbteilungQuery, as, as.inters, v)
}

func (as *AbteilungSelect) sqlScan(ctx context.Context, root *AbteilungQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(as.fns))
	for _, fn := range as.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*as.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := as.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
