// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"viktor/ent/abteilung"
	"viktor/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AbteilungDelete is the builder for deleting a Abteilung entity.
type AbteilungDelete struct {
	config
	hooks    []Hook
	mutation *AbteilungMutation
}

// Where appends a list predicates to the AbteilungDelete builder.
func (ad *AbteilungDelete) Where(ps ...predicate.Abteilung) *AbteilungDelete {
	ad.mutation.Where(ps...)
	return ad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ad *AbteilungDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ad.sqlExec, ad.mutation, ad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ad *AbteilungDelete) ExecX(ctx context.Context) int {
	n, err := ad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ad *AbteilungDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(abteilung.Table, sqlgraph.NewFieldSpec(abteilung.FieldID, field.TypeString))
	if ps := ad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ad.mutation.done = true
	return affected, err
}

// AbteilungDeleteOne is the builder for deleting a single Abteilung entity.
type AbteilungDeleteOne struct {
	ad *AbteilungDelete
}

// Where appends a list predicates to the AbteilungDelete builder.
func (ado *AbteilungDeleteOne) Where(ps ...predicate.Abteilung) *AbteilungDeleteOne {
	ado.ad.mutation.Where(ps...)
	return ado
}

// Exec executes the deletion query.
func (ado *AbteilungDeleteOne) Exec(ctx context.Context) error {
	n, err := ado.ad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{abteilung.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ado *AbteilungDeleteOne) ExecX(ctx context.Context) {
	if err := ado.Exec(ctx); err != nil {
		panic(err)
	}
}
