// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"viktor/ent/abteilung"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Abteilung is the model entity for the Abteilung schema.
type Abteilung struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AbteilungQuery when eager-loading is set.
	Edges        AbteilungEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AbteilungEdges holds the relations/edges for other nodes in the graph.
type AbteilungEdges struct {
	// Mitarbeiters holds the value of the mitarbeiters edge.
	Mitarbeiters []*Mitarbeiter `json:"mitarbeiters,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MitarbeitersOrErr returns the Mitarbeiters value or an error if the edge
// was not loaded in eager-loading.
func (e AbteilungEdges) MitarbeitersOrErr() ([]*Mitarbeiter, error) {
	if e.loadedTypes[0] {
		return e.Mitarbeiters, nil
	}
	return nil, &NotLoadedError{edge: "mitarbeiters"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Abteilung) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case abteilung.FieldID, abteilung.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Abteilung fields.
func (a *Abteilung) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case abteilung.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				a.ID = value.String
			}
		case abteilung.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				a.Name = value.String
			}
		default:
			a.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Abteilung.
// This includes values selected through modifiers, order, etc.
func (a *Abteilung) Value(name string) (ent.Value, error) {
	return a.selectValues.Get(name)
}

// QueryMitarbeiters queries the "mitarbeiters" edge of the Abteilung entity.
func (a *Abteilung) QueryMitarbeiters() *MitarbeiterQuery {
	return NewAbteilungClient(a.config).QueryMitarbeiters(a)
}

// Update returns a builder for updating this Abteilung.
// Note that you need to call Abteilung.Unwrap() before calling this method if this Abteilung
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Abteilung) Update() *AbteilungUpdateOne {
	return NewAbteilungClient(a.config).UpdateOne(a)
}

// Unwrap unwraps the Abteilung entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Abteilung) Unwrap() *Abteilung {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Abteilung is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Abteilung) String() string {
	var builder strings.Builder
	builder.WriteString("Abteilung(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("name=")
	builder.WriteString(a.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Abteilungs is a parsable slice of Abteilung.
type Abteilungs []*Abteilung
