// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"viktor/ent/ansprechpartner"
	"viktor/ent/lieferant"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AnsprechpartnerCreate is the builder for creating a Ansprechpartner entity.
type AnsprechpartnerCreate struct {
	config
	mutation *AnsprechpartnerMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ac *AnsprechpartnerCreate) SetName(s string) *AnsprechpartnerCreate {
	ac.mutation.SetName(s)
	return ac
}

// SetTelefon sets the "telefon" field.
func (ac *AnsprechpartnerCreate) SetTelefon(s string) *AnsprechpartnerCreate {
	ac.mutation.SetTelefon(s)
	return ac
}

// SetNillableTelefon sets the "telefon" field if the given value is not nil.
func (ac *AnsprechpartnerCreate) SetNillableTelefon(s *string) *AnsprechpartnerCreate {
	if s != nil {
		ac.SetTelefon(*s)
	}
	return ac
}

// SetMobil sets the "mobil" field.
func (ac *AnsprechpartnerCreate) SetMobil(s string) *AnsprechpartnerCreate {
	ac.mutation.SetMobil(s)
	return ac
}

// SetNillableMobil sets the "mobil" field if the given value is not nil.
func (ac *AnsprechpartnerCreate) SetNillableMobil(s *string) *AnsprechpartnerCreate {
	if s != nil {
		ac.SetMobil(*s)
	}
	return ac
}

// SetMail sets the "mail" field.
func (ac *AnsprechpartnerCreate) SetMail(s string) *AnsprechpartnerCreate {
	ac.mutation.SetMail(s)
	return ac
}

// SetNillableMail sets the "mail" field if the given value is not nil.
func (ac *AnsprechpartnerCreate) SetNillableMail(s *string) *AnsprechpartnerCreate {
	if s != nil {
		ac.SetMail(*s)
	}
	return ac
}

// SetLieferantId sets the "lieferantId" field.
func (ac *AnsprechpartnerCreate) SetLieferantId(s string) *AnsprechpartnerCreate {
	ac.mutation.SetLieferantId(s)
	return ac
}

// SetNillableLieferantId sets the "lieferantId" field if the given value is not nil.
func (ac *AnsprechpartnerCreate) SetNillableLieferantId(s *string) *AnsprechpartnerCreate {
	if s != nil {
		ac.SetLieferantId(*s)
	}
	return ac
}

// SetID sets the "id" field.
func (ac *AnsprechpartnerCreate) SetID(s string) *AnsprechpartnerCreate {
	ac.mutation.SetID(s)
	return ac
}

// SetLieferantID sets the "lieferant" edge to the Lieferant entity by ID.
func (ac *AnsprechpartnerCreate) SetLieferantID(id string) *AnsprechpartnerCreate {
	ac.mutation.SetLieferantID(id)
	return ac
}

// SetNillableLieferantID sets the "lieferant" edge to the Lieferant entity by ID if the given value is not nil.
func (ac *AnsprechpartnerCreate) SetNillableLieferantID(id *string) *AnsprechpartnerCreate {
	if id != nil {
		ac = ac.SetLieferantID(*id)
	}
	return ac
}

// SetLieferant sets the "lieferant" edge to the Lieferant entity.
func (ac *AnsprechpartnerCreate) SetLieferant(l *Lieferant) *AnsprechpartnerCreate {
	return ac.SetLieferantID(l.ID)
}

// Mutation returns the AnsprechpartnerMutation object of the builder.
func (ac *AnsprechpartnerCreate) Mutation() *AnsprechpartnerMutation {
	return ac.mutation
}

// Save creates the Ansprechpartner in the database.
func (ac *AnsprechpartnerCreate) Save(ctx context.Context) (*Ansprechpartner, error) {
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AnsprechpartnerCreate) SaveX(ctx context.Context) *Ansprechpartner {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AnsprechpartnerCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AnsprechpartnerCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AnsprechpartnerCreate) check() error {
	if _, ok := ac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Ansprechpartner.name"`)}
	}
	return nil
}

func (ac *AnsprechpartnerCreate) sqlSave(ctx context.Context) (*Ansprechpartner, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Ansprechpartner.ID type: %T", _spec.ID.Value)
		}
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AnsprechpartnerCreate) createSpec() (*Ansprechpartner, *sqlgraph.CreateSpec) {
	var (
		_node = &Ansprechpartner{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(ansprechpartner.Table, sqlgraph.NewFieldSpec(ansprechpartner.FieldID, field.TypeString))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.Name(); ok {
		_spec.SetField(ansprechpartner.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ac.mutation.Telefon(); ok {
		_spec.SetField(ansprechpartner.FieldTelefon, field.TypeString, value)
		_node.Telefon = value
	}
	if value, ok := ac.mutation.Mobil(); ok {
		_spec.SetField(ansprechpartner.FieldMobil, field.TypeString, value)
		_node.Mobil = value
	}
	if value, ok := ac.mutation.Mail(); ok {
		_spec.SetField(ansprechpartner.FieldMail, field.TypeString, value)
		_node.Mail = value
	}
	if nodes := ac.mutation.LieferantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ansprechpartner.LieferantTable,
			Columns: []string{ansprechpartner.LieferantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(lieferant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LieferantId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AnsprechpartnerCreateBulk is the builder for creating many Ansprechpartner entities in bulk.
type AnsprechpartnerCreateBulk struct {
	config
	err      error
	builders []*AnsprechpartnerCreate
}

// Save creates the Ansprechpartner entities in the database.
func (acb *AnsprechpartnerCreateBulk) Save(ctx context.Context) ([]*Ansprechpartner, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Ansprechpartner, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnsprechpartnerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AnsprechpartnerCreateBulk) SaveX(ctx context.Context) []*Ansprechpartner {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AnsprechpartnerCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AnsprechpartnerCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
