// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"viktor/ent/ansprechpartner"
	"viktor/ent/lieferant"
	"viktor/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LieferantQuery is the builder for querying Lieferant entities.
type LieferantQuery struct {
	config
	ctx                  *QueryContext
	order                []lieferant.OrderOption
	inters               []Interceptor
	predicates           []predicate.Lieferant
	withAnsprechpartners *AnsprechpartnerQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LieferantQuery builder.
func (lq *LieferantQuery) Where(ps ...predicate.Lieferant) *LieferantQuery {
	lq.predicates = append(lq.predicates, ps...)
	return lq
}

// Limit the number of records to be returned by this query.
func (lq *LieferantQuery) Limit(limit int) *LieferantQuery {
	lq.ctx.Limit = &limit
	return lq
}

// Offset to start from.
func (lq *LieferantQuery) Offset(offset int) *LieferantQuery {
	lq.ctx.Offset = &offset
	return lq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lq *LieferantQuery) Unique(unique bool) *LieferantQuery {
	lq.ctx.Unique = &unique
	return lq
}

// Order specifies how the records should be ordered.
func (lq *LieferantQuery) Order(o ...lieferant.OrderOption) *LieferantQuery {
	lq.order = append(lq.order, o...)
	return lq
}

// QueryAnsprechpartners chains the current query on the "ansprechpartners" edge.
func (lq *LieferantQuery) QueryAnsprechpartners() *AnsprechpartnerQuery {
	query := (&AnsprechpartnerClient{config: lq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lieferant.Table, lieferant.FieldID, selector),
			sqlgraph.To(ansprechpartner.Table, ansprechpartner.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, lieferant.AnsprechpartnersTable, lieferant.AnsprechpartnersColumn),
		)
		fromU = sqlgraph.SetNeighbors(lq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Lieferant entity from the query.
// Returns a *NotFoundError when no Lieferant was found.
func (lq *LieferantQuery) First(ctx context.Context) (*Lieferant, error) {
	nodes, err := lq.Limit(1).All(setContextOp(ctx, lq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lieferant.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lq *LieferantQuery) FirstX(ctx context.Context) *Lieferant {
	node, err := lq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Lieferant ID from the query.
// Returns a *NotFoundError when no Lieferant ID was found.
func (lq *LieferantQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = lq.Limit(1).IDs(setContextOp(ctx, lq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{lieferant.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lq *LieferantQuery) FirstIDX(ctx context.Context) string {
	id, err := lq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Lieferant entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Lieferant entity is found.
// Returns a *NotFoundError when no Lieferant entities are found.
func (lq *LieferantQuery) Only(ctx context.Context) (*Lieferant, error) {
	nodes, err := lq.Limit(2).All(setContextOp(ctx, lq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lieferant.Label}
	default:
		return nil, &NotSingularError{lieferant.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lq *LieferantQuery) OnlyX(ctx context.Context) *Lieferant {
	node, err := lq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Lieferant ID in the query.
// Returns a *NotSingularError when more than one Lieferant ID is found.
// Returns a *NotFoundError when no entities are found.
func (lq *LieferantQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = lq.Limit(2).IDs(setContextOp(ctx, lq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{lieferant.Label}
	default:
		err = &NotSingularError{lieferant.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lq *LieferantQuery) OnlyIDX(ctx context.Context) string {
	id, err := lq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Lieferants.
func (lq *LieferantQuery) All(ctx context.Context) ([]*Lieferant, error) {
	ctx = setContextOp(ctx, lq.ctx, ent.OpQueryAll)
	if err := lq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Lieferant, *LieferantQuery]()
	return withInterceptors[[]*Lieferant](ctx, lq, qr, lq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lq *LieferantQuery) AllX(ctx context.Context) []*Lieferant {
	nodes, err := lq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Lieferant IDs.
func (lq *LieferantQuery) IDs(ctx context.Context) (ids []string, err error) {
	if lq.ctx.Unique == nil && lq.path != nil {
		lq.Unique(true)
	}
	ctx = setContextOp(ctx, lq.ctx, ent.OpQueryIDs)
	if err = lq.Select(lieferant.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lq *LieferantQuery) IDsX(ctx context.Context) []string {
	ids, err := lq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lq *LieferantQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lq.ctx, ent.OpQueryCount)
	if err := lq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lq, querierCount[*LieferantQuery](), lq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lq *LieferantQuery) CountX(ctx context.Context) int {
	count, err := lq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lq *LieferantQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lq.ctx, ent.OpQueryExist)
	switch _, err := lq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lq *LieferantQuery) ExistX(ctx context.Context) bool {
	exist, err := lq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LieferantQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lq *LieferantQuery) Clone() *LieferantQuery {
	if lq == nil {
		return nil
	}
	return &LieferantQuery{
		config:               lq.config,
		ctx:                  lq.ctx.Clone(),
		order:                append([]lieferant.OrderOption{}, lq.order...),
		inters:               append([]Interceptor{}, lq.inters...),
		predicates:           append([]predicate.Lieferant{}, lq.predicates...),
		withAnsprechpartners: lq.withAnsprechpartners.Clone(),
		// clone intermediate query.
		sql:  lq.sql.Clone(),
		path: lq.path,
	}
}

// WithAnsprechpartners tells the query-builder to eager-load the nodes that are connected to
// the "ansprechpartners" edge. The optional arguments are used to configure the query builder of the edge.
func (lq *LieferantQuery) WithAnsprechpartners(opts ...func(*AnsprechpartnerQuery)) *LieferantQuery {
	query := (&AnsprechpartnerClient{config: lq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lq.withAnsprechpartners = query
	return lq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Firma string `json:"Firma,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Lieferant.Query().
//		GroupBy(lieferant.FieldFirma).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (lq *LieferantQuery) GroupBy(field string, fields ...string) *LieferantGroupBy {
	lq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LieferantGroupBy{build: lq}
	grbuild.flds = &lq.ctx.Fields
	grbuild.label = lieferant.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Firma string `json:"Firma,omitempty"`
//	}
//
//	client.Lieferant.Query().
//		Select(lieferant.FieldFirma).
//		Scan(ctx, &v)
func (lq *LieferantQuery) Select(fields ...string) *LieferantSelect {
	lq.ctx.Fields = append(lq.ctx.Fields, fields...)
	sbuild := &LieferantSelect{LieferantQuery: lq}
	sbuild.label = lieferant.Label
	sbuild.flds, sbuild.scan = &lq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LieferantSelect configured with the given aggregations.
func (lq *LieferantQuery) Aggregate(fns ...AggregateFunc) *LieferantSelect {
	return lq.Select().Aggregate(fns...)
}

func (lq *LieferantQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lq); err != nil {
				return err
			}
		}
	}
	for _, f := range lq.ctx.Fields {
		if !lieferant.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lq.path != nil {
		prev, err := lq.path(ctx)
		if err != nil {
			return err
		}
		lq.sql = prev
	}
	return nil
}

func (lq *LieferantQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Lieferant, error) {
	var (
		nodes       = []*Lieferant{}
		_spec       = lq.querySpec()
		loadedTypes = [1]bool{
			lq.withAnsprechpartners != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Lieferant).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Lieferant{config: lq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lq.withAnsprechpartners; query != nil {
		if err := lq.loadAnsprechpartners(ctx, query, nodes,
			func(n *Lieferant) { n.Edges.Ansprechpartners = []*Ansprechpartner{} },
			func(n *Lieferant, e *Ansprechpartner) { n.Edges.Ansprechpartners = append(n.Edges.Ansprechpartners, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lq *LieferantQuery) loadAnsprechpartners(ctx context.Context, query *AnsprechpartnerQuery, nodes []*Lieferant, init func(*Lieferant), assign func(*Lieferant, *Ansprechpartner)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Lieferant)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ansprechpartner.FieldLieferantId)
	}
	query.Where(predicate.Ansprechpartner(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(lieferant.AnsprechpartnersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LieferantId
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "lieferantId" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (lq *LieferantQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lq.querySpec()
	_spec.Node.Columns = lq.ctx.Fields
	if len(lq.ctx.Fields) > 0 {
		_spec.Unique = lq.ctx.Unique != nil && *lq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lq.driver, _spec)
}

func (lq *LieferantQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(lieferant.Table, lieferant.Columns, sqlgraph.NewFieldSpec(lieferant.FieldID, field.TypeString))
	_spec.From = lq.sql
	if unique := lq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if lq.path != nil {
		_spec.Unique = true
	}
	if fields := lq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lieferant.FieldID)
		for i := range fields {
			if fields[i] != lieferant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lq *LieferantQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lq.driver.Dialect())
	t1 := builder.Table(lieferant.Table)
	columns := lq.ctx.Fields
	if len(columns) == 0 {
		columns = lieferant.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lq.sql != nil {
		selector = lq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lq.ctx.Unique != nil && *lq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lq.predicates {
		p(selector)
	}
	for _, p := range lq.order {
		p(selector)
	}
	if offset := lq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LieferantGroupBy is the group-by builder for Lieferant entities.
type LieferantGroupBy struct {
	selector
	build *LieferantQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lgb *LieferantGroupBy) Aggregate(fns ...AggregateFunc) *LieferantGroupBy {
	lgb.fns = append(lgb.fns, fns...)
	return lgb
}

// Scan applies the selector query and scans the result into the given value.
func (lgb *LieferantGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lgb.build.ctx, ent.OpQueryGroupBy)
	if err := lgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LieferantQuery, *LieferantGroupBy](ctx, lgb.build, lgb, lgb.build.inters, v)
}

func (lgb *LieferantGroupBy) sqlScan(ctx context.Context, root *LieferantQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lgb.fns))
	for _, fn := range lgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lgb.flds)+len(lgb.fns))
		for _, f := range *lgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LieferantSelect is the builder for selecting fields of Lieferant entities.
type LieferantSelect struct {
	*LieferantQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ls *LieferantSelect) Aggregate(fns ...AggregateFunc) *LieferantSelect {
	ls.fns = append(ls.fns, fns...)
	return ls
}

// Scan applies the selector query and scans the result into the given value.
func (ls *LieferantSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ls.ctx, ent.OpQuerySelect)
	if err := ls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LieferantQuery, *LieferantSelect](ctx, ls.LieferantQuery, ls, ls.inters, v)
}

func (ls *LieferantSelect) sqlScan(ctx context.Context, root *LieferantQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ls.fns))
	for _, fn := range ls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
