// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"viktor/ent/lieferant"
	"viktor/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LieferantDelete is the builder for deleting a Lieferant entity.
type LieferantDelete struct {
	config
	hooks    []Hook
	mutation *LieferantMutation
}

// Where appends a list predicates to the LieferantDelete builder.
func (ld *LieferantDelete) Where(ps ...predicate.Lieferant) *LieferantDelete {
	ld.mutation.Where(ps...)
	return ld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ld *LieferantDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ld.sqlExec, ld.mutation, ld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ld *LieferantDelete) ExecX(ctx context.Context) int {
	n, err := ld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ld *LieferantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(lieferant.Table, sqlgraph.NewFieldSpec(lieferant.FieldID, field.TypeString))
	if ps := ld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ld.mutation.done = true
	return affected, err
}

// LieferantDeleteOne is the builder for deleting a single Lieferant entity.
type LieferantDeleteOne struct {
	ld *LieferantDelete
}

// Where appends a list predicates to the LieferantDelete builder.
func (ldo *LieferantDeleteOne) Where(ps ...predicate.Lieferant) *LieferantDeleteOne {
	ldo.ld.mutation.Where(ps...)
	return ldo
}

// Exec executes the deletion query.
func (ldo *LieferantDeleteOne) Exec(ctx context.Context) error {
	n, err := ldo.ld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{lieferant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ldo *LieferantDeleteOne) ExecX(ctx context.Context) {
	if err := ldo.Exec(ctx); err != nil {
		panic(err)
	}
}
