// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"viktor/ent/abteilung"
	"viktor/ent/einkauf"
	"viktor/ent/mitarbeiter"
	"viktor/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MitarbeiterQuery is the builder for querying Mitarbeiter entities.
type MitarbeiterQuery struct {
	config
	ctx           *QueryContext
	order         []mitarbeiter.OrderOption
	inters        []Interceptor
	predicates    []predicate.Mitarbeiter
	withAbteilung *AbteilungQuery
	withEinkauf   *EinkaufQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MitarbeiterQuery builder.
func (mq *MitarbeiterQuery) Where(ps ...predicate.Mitarbeiter) *MitarbeiterQuery {
	mq.predicates = append(mq.predicates, ps...)
	return mq
}

// Limit the number of records to be returned by this query.
func (mq *MitarbeiterQuery) Limit(limit int) *MitarbeiterQuery {
	mq.ctx.Limit = &limit
	return mq
}

// Offset to start from.
func (mq *MitarbeiterQuery) Offset(offset int) *MitarbeiterQuery {
	mq.ctx.Offset = &offset
	return mq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mq *MitarbeiterQuery) Unique(unique bool) *MitarbeiterQuery {
	mq.ctx.Unique = &unique
	return mq
}

// Order specifies how the records should be ordered.
func (mq *MitarbeiterQuery) Order(o ...mitarbeiter.OrderOption) *MitarbeiterQuery {
	mq.order = append(mq.order, o...)
	return mq
}

// QueryAbteilung chains the current query on the "abteilung" edge.
func (mq *MitarbeiterQuery) QueryAbteilung() *AbteilungQuery {
	query := (&AbteilungClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mitarbeiter.Table, mitarbeiter.FieldID, selector),
			sqlgraph.To(abteilung.Table, abteilung.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mitarbeiter.AbteilungTable, mitarbeiter.AbteilungColumn),
		)
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEinkauf chains the current query on the "einkauf" edge.
func (mq *MitarbeiterQuery) QueryEinkauf() *EinkaufQuery {
	query := (&EinkaufClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mitarbeiter.Table, mitarbeiter.FieldID, selector),
			sqlgraph.To(einkauf.Table, einkauf.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, mitarbeiter.EinkaufTable, mitarbeiter.EinkaufColumn),
		)
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Mitarbeiter entity from the query.
// Returns a *NotFoundError when no Mitarbeiter was found.
func (mq *MitarbeiterQuery) First(ctx context.Context) (*Mitarbeiter, error) {
	nodes, err := mq.Limit(1).All(setContextOp(ctx, mq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mitarbeiter.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mq *MitarbeiterQuery) FirstX(ctx context.Context) *Mitarbeiter {
	node, err := mq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Mitarbeiter ID from the query.
// Returns a *NotFoundError when no Mitarbeiter ID was found.
func (mq *MitarbeiterQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = mq.Limit(1).IDs(setContextOp(ctx, mq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mitarbeiter.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mq *MitarbeiterQuery) FirstIDX(ctx context.Context) string {
	id, err := mq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Mitarbeiter entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Mitarbeiter entity is found.
// Returns a *NotFoundError when no Mitarbeiter entities are found.
func (mq *MitarbeiterQuery) Only(ctx context.Context) (*Mitarbeiter, error) {
	nodes, err := mq.Limit(2).All(setContextOp(ctx, mq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mitarbeiter.Label}
	default:
		return nil, &NotSingularError{mitarbeiter.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mq *MitarbeiterQuery) OnlyX(ctx context.Context) *Mitarbeiter {
	node, err := mq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Mitarbeiter ID in the query.
// Returns a *NotSingularError when more than one Mitarbeiter ID is found.
// Returns a *NotFoundError when no entities are found.
func (mq *MitarbeiterQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = mq.Limit(2).IDs(setContextOp(ctx, mq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mitarbeiter.Label}
	default:
		err = &NotSingularError{mitarbeiter.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mq *MitarbeiterQuery) OnlyIDX(ctx context.Context) string {
	id, err := mq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Mitarbeiters.
func (mq *MitarbeiterQuery) All(ctx context.Context) ([]*Mitarbeiter, error) {
	ctx = setContextOp(ctx, mq.ctx, ent.OpQueryAll)
	if err := mq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Mitarbeiter, *MitarbeiterQuery]()
	return withInterceptors[[]*Mitarbeiter](ctx, mq, qr, mq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mq *MitarbeiterQuery) AllX(ctx context.Context) []*Mitarbeiter {
	nodes, err := mq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Mitarbeiter IDs.
func (mq *MitarbeiterQuery) IDs(ctx context.Context) (ids []string, err error) {
	if mq.ctx.Unique == nil && mq.path != nil {
		mq.Unique(true)
	}
	ctx = setContextOp(ctx, mq.ctx, ent.OpQueryIDs)
	if err = mq.Select(mitarbeiter.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mq *MitarbeiterQuery) IDsX(ctx context.Context) []string {
	ids, err := mq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mq *MitarbeiterQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mq.ctx, ent.OpQueryCount)
	if err := mq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mq, querierCount[*MitarbeiterQuery](), mq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mq *MitarbeiterQuery) CountX(ctx context.Context) int {
	count, err := mq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mq *MitarbeiterQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mq.ctx, ent.OpQueryExist)
	switch _, err := mq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mq *MitarbeiterQuery) ExistX(ctx context.Context) bool {
	exist, err := mq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MitarbeiterQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mq *MitarbeiterQuery) Clone() *MitarbeiterQuery {
	if mq == nil {
		return nil
	}
	return &MitarbeiterQuery{
		config:        mq.config,
		ctx:           mq.ctx.Clone(),
		order:         append([]mitarbeiter.OrderOption{}, mq.order...),
		inters:        append([]Interceptor{}, mq.inters...),
		predicates:    append([]predicate.Mitarbeiter{}, mq.predicates...),
		withAbteilung: mq.withAbteilung.Clone(),
		withEinkauf:   mq.withEinkauf.Clone(),
		// clone intermediate query.
		sql:  mq.sql.Clone(),
		path: mq.path,
	}
}

// WithAbteilung tells the query-builder to eager-load the nodes that are connected to
// the "abteilung" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *MitarbeiterQuery) WithAbteilung(opts ...func(*AbteilungQuery)) *MitarbeiterQuery {
	query := (&AbteilungClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withAbteilung = query
	return mq
}

// WithEinkauf tells the query-builder to eager-load the nodes that are connected to
// the "einkauf" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *MitarbeiterQuery) WithEinkauf(opts ...func(*EinkaufQuery)) *MitarbeiterQuery {
	query := (&EinkaufClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withEinkauf = query
	return mq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Mitarbeiter.Query().
//		GroupBy(mitarbeiter.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mq *MitarbeiterQuery) GroupBy(field string, fields ...string) *MitarbeiterGroupBy {
	mq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MitarbeiterGroupBy{build: mq}
	grbuild.flds = &mq.ctx.Fields
	grbuild.label = mitarbeiter.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Mitarbeiter.Query().
//		Select(mitarbeiter.FieldName).
//		Scan(ctx, &v)
func (mq *MitarbeiterQuery) Select(fields ...string) *MitarbeiterSelect {
	mq.ctx.Fields = append(mq.ctx.Fields, fields...)
	sbuild := &MitarbeiterSelect{MitarbeiterQuery: mq}
	sbuild.label = mitarbeiter.Label
	sbuild.flds, sbuild.scan = &mq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MitarbeiterSelect configured with the given aggregations.
func (mq *MitarbeiterQuery) Aggregate(fns ...AggregateFunc) *MitarbeiterSelect {
	return mq.Select().Aggregate(fns...)
}

func (mq *MitarbeiterQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mq); err != nil {
				return err
			}
		}
	}
	for _, f := range mq.ctx.Fields {
		if !mitarbeiter.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mq.path != nil {
		prev, err := mq.path(ctx)
		if err != nil {
			return err
		}
		mq.sql = prev
	}
	return nil
}

func (mq *MitarbeiterQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Mitarbeiter, error) {
	var (
		nodes       = []*Mitarbeiter{}
		_spec       = mq.querySpec()
		loadedTypes = [2]bool{
			mq.withAbteilung != nil,
			mq.withEinkauf != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Mitarbeiter).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Mitarbeiter{config: mq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mq.withAbteilung; query != nil {
		if err := mq.loadAbteilung(ctx, query, nodes, nil,
			func(n *Mitarbeiter, e *Abteilung) { n.Edges.Abteilung = e }); err != nil {
			return nil, err
		}
	}
	if query := mq.withEinkauf; query != nil {
		if err := mq.loadEinkauf(ctx, query, nodes, nil,
			func(n *Mitarbeiter, e *Einkauf) { n.Edges.Einkauf = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mq *MitarbeiterQuery) loadAbteilung(ctx context.Context, query *AbteilungQuery, nodes []*Mitarbeiter, init func(*Mitarbeiter), assign func(*Mitarbeiter, *Abteilung)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Mitarbeiter)
	for i := range nodes {
		fk := nodes[i].AbteilungId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(abteilung.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "abteilungId" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (mq *MitarbeiterQuery) loadEinkauf(ctx context.Context, query *EinkaufQuery, nodes []*Mitarbeiter, init func(*Mitarbeiter), assign func(*Mitarbeiter, *Einkauf)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Mitarbeiter)
	for i := range nodes {
		fk := nodes[i].EinkaufId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(einkauf.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "einkaufId" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mq *MitarbeiterQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mq.querySpec()
	_spec.Node.Columns = mq.ctx.Fields
	if len(mq.ctx.Fields) > 0 {
		_spec.Unique = mq.ctx.Unique != nil && *mq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mq.driver, _spec)
}

func (mq *MitarbeiterQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(mitarbeiter.Table, mitarbeiter.Columns, sqlgraph.NewFieldSpec(mitarbeiter.FieldID, field.TypeString))
	_spec.From = mq.sql
	if unique := mq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mq.path != nil {
		_spec.Unique = true
	}
	if fields := mq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mitarbeiter.FieldID)
		for i := range fields {
			if fields[i] != mitarbeiter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if mq.withAbteilung != nil {
			_spec.Node.AddColumnOnce(mitarbeiter.FieldAbteilungId)
		}
		if mq.withEinkauf != nil {
			_spec.Node.AddColumnOnce(mitarbeiter.FieldEinkaufId)
		}
	}
	if ps := mq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mq *MitarbeiterQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mq.driver.Dialect())
	t1 := builder.Table(mitarbeiter.Table)
	columns := mq.ctx.Fields
	if len(columns) == 0 {
		columns = mitarbeiter.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mq.sql != nil {
		selector = mq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mq.ctx.Unique != nil && *mq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mq.predicates {
		p(selector)
	}
	for _, p := range mq.order {
		p(selector)
	}
	if offset := mq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MitarbeiterGroupBy is the group-by builder for Mitarbeiter entities.
type MitarbeiterGroupBy struct {
	selector
	build *MitarbeiterQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mgb *MitarbeiterGroupBy) Aggregate(fns ...AggregateFunc) *MitarbeiterGroupBy {
	mgb.fns = append(mgb.fns, fns...)
	return mgb
}

// Scan applies the selector query and scans the result into the given value.
func (mgb *MitarbeiterGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mgb.build.ctx, ent.OpQueryGroupBy)
	if err := mgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MitarbeiterQuery, *MitarbeiterGroupBy](ctx, mgb.build, mgb, mgb.build.inters, v)
}

func (mgb *MitarbeiterGroupBy) sqlScan(ctx context.Context, root *MitarbeiterQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mgb.fns))
	for _, fn := range mgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mgb.flds)+len(mgb.fns))
		for _, f := range *mgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MitarbeiterSelect is the builder for selecting fields of Mitarbeiter entities.
type MitarbeiterSelect struct {
	*MitarbeiterQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ms *MitarbeiterSelect) Aggregate(fns ...AggregateFunc) *MitarbeiterSelect {
	ms.fns = append(ms.fns, fns...)
	return ms
}

// Scan applies the selector query and scans the result into the given value.
func (ms *MitarbeiterSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ms.ctx, ent.OpQuerySelect)
	if err := ms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MitarbeiterQuery, *MitarbeiterSelect](ctx, ms.MitarbeiterQuery, ms, ms.inters, v)
}

func (ms *MitarbeiterSelect) sqlScan(ctx context.Context, root *MitarbeiterQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ms.fns))
	for _, fn := range ms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
