// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"viktor/ent/pdf"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Pdf is the model entity for the Pdf schema.
type Pdf struct {
	config `json:"-"`
	// ID of the ent.
	ID int32 `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Body holds the value of the "body" field.
	Body         string `json:"body,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Pdf) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pdf.FieldID:
			values[i] = new(sql.NullInt64)
		case pdf.FieldTitle, pdf.FieldBody:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Pdf fields.
func (pd *Pdf) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pdf.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pd.ID = int32(value.Int64)
		case pdf.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				pd.Title = value.String
			}
		case pdf.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				pd.Body = value.String
			}
		default:
			pd.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Pdf.
// This includes values selected through modifiers, order, etc.
func (pd *Pdf) Value(name string) (ent.Value, error) {
	return pd.selectValues.Get(name)
}

// Update returns a builder for updating this Pdf.
// Note that you need to call Pdf.Unwrap() before calling this method if this Pdf
// was returned from a transaction, and the transaction was committed or rolled back.
func (pd *Pdf) Update() *PdfUpdateOne {
	return NewPdfClient(pd.config).UpdateOne(pd)
}

// Unwrap unwraps the Pdf entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pd *Pdf) Unwrap() *Pdf {
	_tx, ok := pd.config.driver.(*txDriver)
	if !ok {
		panic("ent: Pdf is not a transactional entity")
	}
	pd.config.driver = _tx.drv
	return pd
}

// String implements the fmt.Stringer.
func (pd *Pdf) String() string {
	var builder strings.Builder
	builder.WriteString("Pdf(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pd.ID))
	builder.WriteString("title=")
	builder.WriteString(pd.Title)
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(pd.Body)
	builder.WriteByte(')')
	return builder.String()
}

// Pdfs is a parsable slice of Pdf.
type Pdfs []*Pdf
