// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"viktor/ent/predicate"
	"viktor/ent/statu"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StatuUpdate is the builder for updating Statu entities.
type StatuUpdate struct {
	config
	hooks    []Hook
	mutation *StatuMutation
}

// Where appends a list predicates to the StatuUpdate builder.
func (su *StatuUpdate) Where(ps ...predicate.Statu) *StatuUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetStatus sets the "status" field.
func (su *StatuUpdate) SetStatus(s string) *StatuUpdate {
	su.mutation.SetStatus(s)
	return su
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (su *StatuUpdate) SetNillableStatus(s *string) *StatuUpdate {
	if s != nil {
		su.SetStatus(*s)
	}
	return su
}

// SetSince sets the "since" field.
func (su *StatuUpdate) SetSince(s string) *StatuUpdate {
	su.mutation.SetSince(s)
	return su
}

// SetNillableSince sets the "since" field if the given value is not nil.
func (su *StatuUpdate) SetNillableSince(s *string) *StatuUpdate {
	if s != nil {
		su.SetSince(*s)
	}
	return su
}

// Mutation returns the StatuMutation object of the builder.
func (su *StatuUpdate) Mutation() *StatuMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *StatuUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *StatuUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StatuUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StatuUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *StatuUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(statu.Table, statu.Columns, sqlgraph.NewFieldSpec(statu.FieldID, field.TypeInt32))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Status(); ok {
		_spec.SetField(statu.FieldStatus, field.TypeString, value)
	}
	if value, ok := su.mutation.Since(); ok {
		_spec.SetField(statu.FieldSince, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// StatuUpdateOne is the builder for updating a single Statu entity.
type StatuUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StatuMutation
}

// SetStatus sets the "status" field.
func (suo *StatuUpdateOne) SetStatus(s string) *StatuUpdateOne {
	suo.mutation.SetStatus(s)
	return suo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (suo *StatuUpdateOne) SetNillableStatus(s *string) *StatuUpdateOne {
	if s != nil {
		suo.SetStatus(*s)
	}
	return suo
}

// SetSince sets the "since" field.
func (suo *StatuUpdateOne) SetSince(s string) *StatuUpdateOne {
	suo.mutation.SetSince(s)
	return suo
}

// SetNillableSince sets the "since" field if the given value is not nil.
func (suo *StatuUpdateOne) SetNillableSince(s *string) *StatuUpdateOne {
	if s != nil {
		suo.SetSince(*s)
	}
	return suo
}

// Mutation returns the StatuMutation object of the builder.
func (suo *StatuUpdateOne) Mutation() *StatuMutation {
	return suo.mutation
}

// Where appends a list predicates to the StatuUpdate builder.
func (suo *StatuUpdateOne) Where(ps ...predicate.Statu) *StatuUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *StatuUpdateOne) Select(field string, fields ...string) *StatuUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Statu entity.
func (suo *StatuUpdateOne) Save(ctx context.Context) (*Statu, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StatuUpdateOne) SaveX(ctx context.Context) *Statu {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *StatuUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StatuUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *StatuUpdateOne) sqlSave(ctx context.Context) (_node *Statu, err error) {
	_spec := sqlgraph.NewUpdateSpec(statu.Table, statu.Columns, sqlgraph.NewFieldSpec(statu.FieldID, field.TypeInt32))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Statu.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, statu.FieldID)
		for _, f := range fields {
			if !statu.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != statu.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Status(); ok {
		_spec.SetField(statu.FieldStatus, field.TypeString, value)
	}
	if value, ok := suo.mutation.Since(); ok {
		_spec.SetField(statu.FieldSince, field.TypeString, value)
	}
	_node = &Statu{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
