// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"viktor/ent/predicate"
	"viktor/ent/warenlieferung"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WarenlieferungDelete is the builder for deleting a Warenlieferung entity.
type WarenlieferungDelete struct {
	config
	hooks    []Hook
	mutation *WarenlieferungMutation
}

// Where appends a list predicates to the WarenlieferungDelete builder.
func (wd *WarenlieferungDelete) Where(ps ...predicate.Warenlieferung) *WarenlieferungDelete {
	wd.mutation.Where(ps...)
	return wd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wd *WarenlieferungDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, wd.sqlExec, wd.mutation, wd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (wd *WarenlieferungDelete) ExecX(ctx context.Context) int {
	n, err := wd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wd *WarenlieferungDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(warenlieferung.Table, sqlgraph.NewFieldSpec(warenlieferung.FieldID, field.TypeInt32))
	if ps := wd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	wd.mutation.done = true
	return affected, err
}

// WarenlieferungDeleteOne is the builder for deleting a single Warenlieferung entity.
type WarenlieferungDeleteOne struct {
	wd *WarenlieferungDelete
}

// Where appends a list predicates to the WarenlieferungDelete builder.
func (wdo *WarenlieferungDeleteOne) Where(ps ...predicate.Warenlieferung) *WarenlieferungDeleteOne {
	wdo.wd.mutation.Where(ps...)
	return wdo
}

// Exec executes the deletion query.
func (wdo *WarenlieferungDeleteOne) Exec(ctx context.Context) error {
	n, err := wdo.wd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{warenlieferung.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wdo *WarenlieferungDeleteOne) ExecX(ctx context.Context) {
	if err := wdo.Exec(ctx); err != nil {
		panic(err)
	}
}
