// Code generated by ent, DO NOT EDIT.

package statu

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the statu type in the database.
	Label = "statu"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSince holds the string denoting the since field in the database.
	FieldSince = "since"
	// Table holds the table name of the statu in the database.
	Table = "Status"
)

// Columns holds all SQL columns for statu fields.
var Columns = []string{
	FieldID,
	FieldStatus,
	FieldSince,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Statu queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySince orders the results by the since field.
func BySince(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSince, opts...).ToFunc()
}
