// Code generated by ent, DO NOT EDIT.

package aussteller

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the aussteller type in the database.
	Label = "aussteller"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldArtikelnummer holds the string denoting the artikelnummer field in the database.
	FieldArtikelnummer = "artikelnummer"
	// FieldArtikelname holds the string denoting the artikelname field in the database.
	FieldArtikelname = "artikelname"
	// FieldSpecs holds the string denoting the specs field in the database.
	FieldSpecs = "specs"
	// FieldPreis holds the string denoting the preis field in the database.
	FieldPreis = "preis"
	// FieldBild holds the string denoting the bild field in the database.
	FieldBild = "bild"
	// Table holds the table name of the aussteller in the database.
	Table = "Aussteller"
)

// Columns holds all SQL columns for aussteller fields.
var Columns = []string{
	FieldID,
	FieldArtikelnummer,
	FieldArtikelname,
	FieldSpecs,
	FieldPreis,
	FieldBild,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Aussteller queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByArtikelnummer orders the results by the Artikelnummer field.
func ByArtikelnummer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArtikelnummer, opts...).ToFunc()
}

// ByArtikelname orders the results by the Artikelname field.
func ByArtikelname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArtikelname, opts...).ToFunc()
}

// BySpecs orders the results by the Specs field.
func BySpecs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpecs, opts...).ToFunc()
}

// ByPreis orders the results by the Preis field.
func ByPreis(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPreis, opts...).ToFunc()
}

// ByBild orders the results by the Bild field.
func ByBild(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBild, opts...).ToFunc()
}
