// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../db/models.js";

export class Geburtstagsliste {
    /**
     * Creates a new Geburtstagsliste instance.
     * @param {Partial<Geburtstagsliste>} [$$source = {}] - The source object to create the Geburtstagsliste.
     */
    constructor($$source = {}) {
        if (!("Vergangen" in $$source)) {
            /**
             * @member
             * @type {db$0.Mitarbeiter[]}
             */
            this["Vergangen"] = [];
        }
        if (!("Heute" in $$source)) {
            /**
             * @member
             * @type {db$0.Mitarbeiter[]}
             */
            this["Heute"] = [];
        }
        if (!("Zukunft" in $$source)) {
            /**
             * @member
             * @type {db$0.Mitarbeiter[]}
             */
            this["Zukunft"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Geburtstagsliste instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Geburtstagsliste}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Vergangen" in $$parsedSource) {
            $$parsedSource["Vergangen"] = $$createField0_0($$parsedSource["Vergangen"]);
        }
        if ("Heute" in $$parsedSource) {
            $$parsedSource["Heute"] = $$createField1_0($$parsedSource["Heute"]);
        }
        if ("Zukunft" in $$parsedSource) {
            $$parsedSource["Zukunft"] = $$createField2_0($$parsedSource["Zukunft"]);
        }
        return new Geburtstagsliste(/** @type {Partial<Geburtstagsliste>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = db$0.Mitarbeiter.createFrom;
const $$createType1 = $Create.Array($$createType0);
