// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSession() {
  return window['go']['main']['App']['CheckSession']();
}

export function Create(arg1, arg2) {
  return window['go']['main']['App']['Create'](arg1, arg2);
}

export function Delete(arg1, arg2, arg3) {
  return window['go']['main']['App']['Delete'](arg1, arg2, arg3);
}

export function DownloadArchive(arg1) {
  return window['go']['main']['App']['DownloadArchive'](arg1);
}

export function Einkaufsliste() {
  return window['go']['main']['App']['Einkaufsliste']();
}

export function Geburtstagsliste() {
  return window['go']['main']['App']['Geburtstagsliste']();
}

export function GetKundeWithKundennummer(arg1) {
  return window['go']['main']['App']['GetKundeWithKundennummer'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Read(arg1, arg2, arg3) {
  return window['go']['main']['App']['Read'](arg1, arg2, arg3);
}

export function Reload() {
  return window['go']['main']['App']['Reload']();
}

export function SearchArchive(arg1) {
  return window['go']['main']['App']['SearchArchive'](arg1);
}

export function SearchSage(arg1) {
  return window['go']['main']['App']['SearchSage'](arg1);
}

export function Update(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Update'](arg1, arg2, arg3, arg4);
}

export function UploadImage(arg1, arg2) {
  return window['go']['main']['App']['UploadImage'](arg1, arg2);
}
