// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function Create(arg1:db.Model,arg2:any):Promise<boolean>;

export function Delete(arg1:db.Model,arg2:any,arg3:any):Promise<boolean>;

export function Einkaufsliste():Promise<Array<db.MitarbeiterModel>>;

export function Geburtstagsliste():Promise<db.GeburtstagsListe>;

export function Read(arg1:db.Model,arg2:any,arg3:any):Promise<any>;

export function Update(arg1:db.Model,arg2:any,arg3:any,arg4:any):Promise<boolean>;

export function UploadImage(arg1:string,arg2:number):Promise<boolean>;
