// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Abteilung is the predicate function for abteilung builders.
type Abteilung func(*sql.Selector)

// Angebot is the predicate function for angebot builders.
type Angebot func(*sql.Selector)

// Ansprechpartner is the predicate function for ansprechpartner builders.
type Ansprechpartner func(*sql.Selector)

// Aussteller is the predicate function for aussteller builders.
type Aussteller func(*sql.Selector)

// Einkauf is the predicate function for einkauf builders.
type Einkauf func(*sql.Selector)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)

// Lieferant is the predicate function for lieferant builders.
type Lieferant func(*sql.Selector)

// Mitarbeiter is the predicate function for mitarbeiter builders.
type Mitarbeiter func(*sql.Selector)

// Partner is the predicate function for partner builders.
type Partner func(*sql.Selector)

// Pdf is the predicate function for pdf builders.
type Pdf func(*sql.Selector)

// Statu is the predicate function for statu builders.
type Statu func(*sql.Selector)

// Warenlieferung is the predicate function for warenlieferung builders.
type Warenlieferung func(*sql.Selector)
